name: bomatrack
description: "A Property Management App."
publish_to: 'none'
version: 2.2.8

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  google_sign_in: ^6.2.2
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flow_builder: ^0.1.0
  formz: ^0.8.0
  google_fonts: ^6.2.1
  animations: ^2.0.11
  pinput: ^5.0.0
  flutter_sticky_header: ^0.7.0
  shimmer: ^3.0.0
  provider: ^6.1.2
  collection: ^1.18.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/google_fonts/
    - lib/assets/images/logo.png
    - lib/assets/images/brand.png
    - lib/assets/images/google_icon.png
    - lib/assets/svg/building_svg.svg
    - lib/assets/svg/user_placeholder_svg.svg
    - lib/assets/svg/add_people.svg
