// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeXChbSE6Fv8eCO9eX8Q2xeZGy5Pblhzc',
    appId: '1:819023357120:web:9a9c43a04a0dd767b5f925',
    messagingSenderId: '819023357120',
    projectId: 'test-rayroyal3',
    authDomain: 'test-rayroyal3.firebaseapp.com',
    storageBucket: 'test-rayroyal3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC39afYwZ-2fMUvfdr6g4S4lx8zreruTx4',
    appId: '1:819023357120:android:a8e7cbc6f5f9f5d6b5f925',
    messagingSenderId: '819023357120',
    projectId: 'test-rayroyal3',
    storageBucket: 'test-rayroyal3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJfwF6JtmUqZe0FBmBwu4MCNV5rHrN2k',
    appId: '1:819023357120:ios:634b7c2eb12808a4b5f925',
    messagingSenderId: '819023357120',
    projectId: 'test-rayroyal3',
    storageBucket: 'test-rayroyal3.firebasestorage.app',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEJfwF6JtmUqZe0FBmBwu4MCNV5rHrN2k',
    appId: '1:819023357120:ios:634b7c2eb12808a4b5f925',
    messagingSenderId: '819023357120',
    projectId: 'test-rayroyal3',
    storageBucket: 'test-rayroyal3.firebasestorage.app',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeXChbSE6Fv8eCO9eX8Q2xeZGy5Pblhzc',
    appId: '1:819023357120:web:07e80dbafc3b033ab5f925',
    messagingSenderId: '819023357120',
    projectId: 'test-rayroyal3',
    authDomain: 'test-rayroyal3.firebaseapp.com',
    storageBucket: 'test-rayroyal3.firebasestorage.app',
  );
}
